---
abstract: 'Access your wesabe.com account information'
author:
  - 'Brian Cassidy <bricas@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Finance-Wesabe
no_index:
  directory:
    - inc
    - t
requires:
  DateTime::Format::ISO8601: 0
  LWP::UserAgent: 0
  Moose: 0.51
  URI: 0
  XML::Simple: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
